---
- name: Deploy New Landing Page to Apache VM
  hosts: apache_servers
  become: true
  tasks:
    - name: Copy index.html to Apache web directory
      ansible.builtin.copy:
        src: ./index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
